### ISSUE TITLE
Widget not configured properly. Text does not resize

### ISSUE THREAD

**Issue by LEMUSADR000** [lzhuor/auto_size_text_field#21] opened 2021-05-27 00:02 UTC
I have the widget code as such:

```
return Row(
   children: <Widget>[
     Expanded(
       child: AutoSizeTextField(
         controller: TextEditingController(text: name),
         decoration: InputDecoration(
           hintText: "Name",
         ),
       ),
     ),
   ],
 );
```
    
When I enter input it scrolls to the right but does not limit the size of the input in any way. Why is this?

I've also tried

```
SizedBox(
  child: AutoSizeTextField(
    controller: TextEditingController(text: name),
    decoration: InputDecoration(
      hintText: "Name",
    ),
  ),
  width: 200,
);
```

And get the same results but in a smaller box. Are there some theme data that I need to provide? What is going on. Currently this works 0% of the time.

**Comment by manylittlestorms** [comment] 2021-11-24 23:07
Same issue...

**Comment by DowsingUK** [comment] 2021-11-26 04:27
Same here...

**Comment by manylittlestorms** [comment] 2021-11-26 12:07
@lzhuor Any chance you could look into this? I have a Row --> Expanded --> AutoSizeTextField like OP, but it doesn't resize.

**Comment by lzhuor** [comment] 2021-12-15 09:27
Hi @DowsingUK, please bear in mind that the parent has to be a constrained Box element in Flutter otherwise this widget does not work. 

Hi @manylittlestorms, `Row` -> `Expanded` -> `AutoSizeTextField` should wor. Did you try to inspect the element and see if size constraints are in the properties of the `Widget` element?

Further more:
Could you please try the following?
- Does the example in this project works?
- Share a screenshot of the code or paste the code snippet?
- Take a screen recording of the flow if possible?

**Comment by DowsingUK** [comment] 2021-12-15 16:45
Good day, it's working very well in other devices, lately I tried with a AndroidTV in a huge screen an it worked like a charm, but in some tablets and some iPhones Plus it is not working at all I even have tried compiling the example as it is and no one single textfield has being resized on those devices

**Comment by lzhuor** [comment] 2021-12-18 08:32
Hi @DowsingUK I might roughly find the root cause. Will share more details later. Thanks to my teammate!

**Comment by DowsingUK** [comment] 2021-12-18 17:42
Great we all be waiting, thank you so much!

**Comment by manylittlestorms** [comment] 2021-12-18 17:43
> Hi @DowsingUK I might roughly find the root cause. Will share more details later. Thanks to my teammate!

Thank you. Waiting for a fix.

**Comment by Raph22** [comment] 2021-12-29 23:43
Hello, 
I m not sure it's related to that issue but for me the example (https://github.com/lzhuor/auto_size_text_field/blob/master/example/lib/main.dart) doesn't work except the last one, "multi line text with input padding".
I don't need the multi lines usage in my case but for those who are interested I make it working with one line input by removing `maxWidth: constraintWidth` from `tp.layout` line 790. But it breaks the multi lines. Maybe I'll try to open a PR to solve that issue as well but I m new to Dart and Flutter and not a lot of free time to do.
Also, about the first example given by the author of the issue, I notice that the controller shouldn't be initialize when passed to the constructor `AutoSizeTextField` but be declared before in a variable and pass it to the constructor.
I m using a Galaxy S10 with Android 11.
Otherwise thanks for that package 😄

**Comment by lzhuor** [comment] 2021-12-30 19:43
Hi @Raph22 Thank you very much for the explanation. I am sorry that my day job has been making me occupied due to year-end stuff. Looking forward to your PR and thank you for the kind words!

**Comment by lzhuor** [comment] 2022-01-26 06:29
Closed as no more follow-ups with the provided solution.

**Comment by pomarec** [comment] 2022-11-24 09:57
Where does the value `280` comes from ? You have to know the value of the width beforhand ? It is the anti-usage of `Expanded` in a `Row` in my understanding.

**Comment by manylittlestorms** [comment] 2022-11-24 10:01
> Hi @DowsingUK @manylittlestorms  @Raph22 @LEMUSADR000 , I found that for some Android 11 and above devices, we have to explicitly set the `constraints` to get it to work. The temporary workaround is:
> 
> ```dart
> 
> Container(
> 
>     constraints: BoxConstraints(maxWidth: 280),
> 
>     child: AutoSizeTextField()
> 
> )
> 
> ```

Having to set a constraint is a problem, since we wanted to use Expanded because we don't know how much width it will get...

**Comment by pomarec** [comment] 2023-01-03 08:46
@lzhuor Do you think this issue should be re-opened ? The provided solution is actually not a solution but a fake workaround as explained by @manylittlestorms

**Comment by manylittlestorms** [comment] 2023-01-03 13:44
> @lzhuor Do you think this issue should be re-opened ? The provided solution is actually not a solution but a fake workaround as explained by @manylittlestorms 

It should be re-opened in my opinion. @lzhuor

**Comment by JohnnyRainbow81** [comment] 2023-03-29 15:53
Same issue here.

**Comment by lzhuor** [comment] 2023-04-13 06:37
Hi buddies, how this widget works is that it detects the box constraints to compute the optimal textual size. 

It's impossible to know the optimal textual size without box constraints. As you mentioned, with `<Expanded />` this widget expects to know the boundary constraint but does not. 

This is likely a seaparet issue in Flutter instead of this library. Would love to discuss with you.

**Closed by lzhuor** 2023-04-13 06:37 UTC
Labels: bug
